---
driver:
#  name: vagrant
  name: docker

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
#  - name: ubuntu-14.04
  - name: centos-6.7
    driver_config:
      image: centos:6.7
      platform: centos
#  - name: oracle_linux6
#    driver_config:
#      image: oraclelinux:6
#      platform: rhel
suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
