name 'myhaproxy'
maintainer 'Carlos Picazo'
maintainer_email 'cpikzo@gmail.com'
license 'copyright minabo'
description 'Installs/Configures myhaproxy'
long_description 'Installs/Configures myhaproxy'
version '1.0.0'
depends 'haproxy', '~> 1.6.7'
